# Configuration file for the Sphinx documentation builder.
# https://www.sphinx-doc.org/en/master/usage/configuration.html
# Generated by: ./iclaude.sh --init-docs

# -- Project information -------------------------------------------------------
project = "aihub"
author = "aihub contributors"

# -- General configuration -----------------------------------------------------
extensions = [
    "myst_parser",
    "sphinx_design",
    "sphinx_copybutton",
    "sphinxcontrib.mermaid",
]

# sphinx-llms-txt: generates llms.txt and llms-full.txt for AI agents
# Install: pip install sphinx-llms-txt
try:
    import sphinx_llms_txt  # noqa: F401
    extensions.append("sphinx_llms_txt")
except ImportError:
    pass  # Optional — docs build without it

# MyST Parser — use Markdown with full Sphinx capabilities
myst_enable_extensions = [
    "colon_fence",   # ::: blocks as alternative to ``` for directives
    "deflist",       # Definition lists
    "fieldlist",     # Field lists
    "attrs_inline",  # Inline attributes {.class}
]

# Generate anchors for all heading levels (fixes cross-reference warnings)
myst_heading_anchors = 4

# Treat ```mermaid fences as {mermaid} directives
myst_fence_as_directive = ["mermaid"]

# File formats
source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

# Exclude patterns (relative to source root = docs/)
exclude_patterns = [
    "sphinx/_build",
    "sphinx/index.md",
    "Thumbs.db",
    ".DS_Store",
    "plans",
    "llms.txt",
    "llms-full.txt",
]

# -- HTML output ---------------------------------------------------------------
html_theme = "furo"
html_title = "aihub Documentation"

# Furo theme options
html_theme_options = {
    "sidebar_hide_name": False,
    "navigation_with_keys": True,
}

# Root document — relative to source directory (docs/ when built with -c docs/sphinx/)
# Build script uses docs/ as source root when root_doc is set in conf.py
root_doc = "index"

# -- sphinx-llms-txt -----------------------------------------------------------
# AI-first documentation: generates llms.txt and llms-full.txt
# These files allow AI agents to consume documentation efficiently
# See: https://llmstxt.org/
